version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Net.Compilers
    versions:
    - 3.8.0
  - dependency-name: Microsoft.ApplicationInsights.WindowsServer
    versions:
    - 2.16.0
  - dependency-name: Microsoft.Rest.ClientRuntime
    versions:
    - 2.3.22
  - dependency-name: Microsoft.IdentityModel.Clients.ActiveDirectory
    versions:
    - 5.2.8
  - dependency-name: AspNet.ScriptManager.jQuery
    versions:
    - 3.5.1
  - dependency-name: jQuery
    versions:
    - 3.5.1
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
